sample_data = {'HGTV_HD_EAST': {201521726: {'casu_adid': 5264,
                                            'instime': '00:22:46',
                                            'cpsu': [{'cpsu_adid': '5264',
                                                      'duration': '27.04',
                                                      'flag_mask': '1',
                                                      'full_play_flag': '1',
                                                      'profile': '020201000000',
                                                      'sdv_result': '1',
                                                      'stb_mac': '000005899e04'},
                                                     {'cpsu_adid': 5264,
                                                      'duration': 27.04,
                                                      'flag_mask': 1,
                                                      'full_play_flag': 1,
                                                      'profile': 20201000000,
                                                      'sdv_result': 1,
                                                      'stb_mac': '00000146d738'}]}
                                },
               'NatGeo_HD_EAST': {201521727: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '00:22:46'},
                                  201521728: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '00:43:35'},
                                  201521733: {'casu_adid': 5264,
                                              'cpsu': [{'cpsu_adid': 5264,
                                                        'duration': 27.04,
                                                        'flag_mask': 1,
                                                        'full_play_flag': 1,
                                                        'profile': 0,
                                                        'sdv_result': 0,
                                                        'stb_mac': '3438b7c57768'}],
                                              'instime': '05:21:36'},
                                  201521734: {'casu_adid': 5264,
                                              'cpsu': [{'cpsu_adid': 5264,
                                                        'duration': 27.04,
                                                        'flag_mask': 1,
                                                        'full_play_flag': 1,
                                                        'profile': 0,
                                                        'sdv_result': 0,
                                                        'stb_mac': '3438b7c57204'}],
                                              'instime': '05:41:31'},
                                  201521737: {'casu_adid': 5264,
                                              'cpsu': [{'cpsu_adid': 5264,
                                                        'duration': 27.04,
                                                        'flag_mask': 1,
                                                        'full_play_flag': 1,
                                                        'profile': 0,
                                                        'sdv_result': 0,
                                                        'stb_mac': '3438b7c57204'}],
                                              'instime': '06:24:06'},
                                  201521738: {'casu_adid': 5264,
                                              'cpsu': [{'cpsu_adid': 5264,
                                                        'duration': 27.04,
                                                        'flag_mask': 1,
                                                        'full_play_flag': 1,
                                                        'profile': 0,
                                                        'sdv_result': 0,
                                                        'stb_mac': '3438b7c57204'}],
                                              'instime': '06:40:17'},
                                  201521741: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '07:24:08'},
                                  201521742: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '07:41:47'},
                                  201521745: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '08:24:53'},
                                  201521747: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '08:45:50'},
                                  201521749: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '09:22:40'},
                                  201521751: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '09:41:20'},
                                  201521753: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '10:25:37'},
                                  201521754: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '10:42:28'},
                                  201521757: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '11:25:20'},
                                  201521758: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '11:41:33'},
                                  201521761: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '12:25:15'},
                                  201521763: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '12:44:35'},
                                  201521765: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '13:22:59'},
                                  201521767: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '13:44:39'},
                                  201521769: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '14:23:31'},
                                  201521771: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '14:44:05'},
                                  201521773: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '15:24:12'},
                                  201521775: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '15:44:07'},
                                  201521777: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '16:25:50'},
                                  201521779: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '16:43:08'},
                                  201521781: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '17:23:37'},
                                  201521783: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '17:43:51'},
                                  201521785: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '18:22:40'},
                                  201521787: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '18:44:30'},
                                  201521789: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '19:21:45'},
                                  201521791: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '19:40:04'},
                                  201521793: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '20:25:26'},
                                  201521795: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '20:44:15'},
                                  201521797: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '21:22:40'},
                                  201521798: {'casu_adid': 5264,
                                              'cpsu': [],
                                              'instime': '21:44:30'}}}

import os
from config import db
from models import Channel, BreakId, Cpsu, BreakIdSchema
import sys

# Delete database file if it exists currently
if os.path.exists("ldai_backend.db"):
    os.remove("ldai_backend.db")

# Create the database
db.create_all()

# iterate over the PEOPLE structure and populate the database
# for channel in sample_data:
#     chann = Channel(channel=channel)
#     for breakid in sample_data[channel]:
#         chann.breakid.append(BreakId(breakid=breakid, casu_adid=sample_data[channel][breakid].get('casu_adid'),
#                                      instime=sample_data[channel][breakid].get('instime')))
#         # br = BreakId(breakid=breakid, casu_adid=sample_data[channel][breakid].get('casu_adid'), instime=sample_data[channel][breakid].get('instime'))
#         db.session.add(chann)
#         for cpsu_info in sample_data[channel][breakid]['cpsu']:
#             if cpsu_info:
#                 print(cpsu_info)
#                 cpsu = Cpsu(breakid_id=BreakId.query.filter(BreakId.breakid == breakid).one_or_none().breakid_id,
#                             duration=cpsu_info.get('duration'),
#                             flag_mask=cpsu_info.get('flag_mask'),
#                             full_play_flag=cpsu_info.get('full_play_flag'),
#                             profile=cpsu_info.get('profile'),
#                             sdv_result=cpsu_info.get('sdv_result'),
#                             stb_mac=cpsu_info.get('stb_mac'))
#                 db.session.add(cpsu)
#
#             else:
#                 print("none")

db.session.commit()
